-- تقييم الضيوف بعد الخروج (من طرف الموظفين) + قائمة حظر الضيوف بالجوال.
--
-- ملاحظة: يحاول هذا الملف استخدام current_owner_id() / is_platform_admin() من
-- 0001_multi_tenant.sql إن كانت موجودة على قاعدة البيانات (عزل حسب المالك)،
-- وإلا يرجع تلقائياً لسياسة تسمح بالوصول الكامل للمستخدمين المسجّلين (authenticated)
-- بنفس نمط بقية الجداول الحالية — حتى لا يفشل التنفيذ إذا لم تُطبَّق 0001 على هذه القاعدة.

create table if not exists guest_ratings (
  id         bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete set null,
  chalet     text not null,
  guest      text not null,
  phone      text,
  rating     smallint not null check (rating between 1 and 5),
  note       text,
  owner_id   uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists guest_ratings_owner_id_idx on guest_ratings(owner_id);
create index if not exists guest_ratings_phone_idx    on guest_ratings(phone);

create table if not exists blocked_guests (
  id         bigint generated by default as identity primary key,
  phone      text not null,
  guest      text not null,
  reason     text,
  owner_id   uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (owner_id, phone)
);
create index if not exists blocked_guests_owner_id_idx on blocked_guests(owner_id);
create index if not exists blocked_guests_phone_idx    on blocked_guests(phone);

alter table guest_ratings  enable row level security;
alter table blocked_guests enable row level security;

do $$
begin
  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where p.proname = 'current_owner_id' and n.nspname = 'public'
  ) then
    drop policy if exists guest_ratings_tenant_isolation on guest_ratings;
    execute $sql$
      create policy guest_ratings_tenant_isolation on guest_ratings for all
        using (owner_id = current_owner_id() or is_platform_admin())
        with check (owner_id = current_owner_id() or is_platform_admin())
    $sql$;

    drop policy if exists blocked_guests_tenant_isolation on blocked_guests;
    execute $sql$
      create policy blocked_guests_tenant_isolation on blocked_guests for all
        using (owner_id = current_owner_id() or is_platform_admin())
        with check (owner_id = current_owner_id() or is_platform_admin())
    $sql$;
  else
    drop policy if exists guest_ratings_authenticated on guest_ratings;
    create policy guest_ratings_authenticated on guest_ratings for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');

    drop policy if exists blocked_guests_authenticated on blocked_guests;
    create policy blocked_guests_authenticated on blocked_guests for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;
end $$;
