-- إدارة المستثمرين: لكل شاليه أعضاء مختلفين ونسب أرباح مختلفة.
-- مكتوب بحيث يتعامل بأمان مع جدول investors موجود مسبقاً بأي شكل —
-- يضيف الأعمدة الناقصة فقط، بدون افتراض إن الجدول أُنشئ من الصفر بهذا الملف.

create table if not exists investors (
  id bigint generated by default as identity primary key
);

alter table investors add column if not exists chalet     text;
alter table investors add column if not exists name       text;
alter table investors add column if not exists phone      text;
alter table investors add column if not exists percentage numeric not null default 0;
alter table investors add column if not exists note       text;
alter table investors add column if not exists owner_id   uuid references auth.users(id);
alter table investors add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'investors_percentage_check') then
    begin
      alter table investors add constraint investors_percentage_check check (percentage >= 0 and percentage <= 100);
    exception when check_violation then
      raise notice 'skipping investors_percentage_check: existing rows out of range';
    end;
  end if;
end $$;

create index if not exists investors_owner_id_idx on investors(owner_id);
create index if not exists investors_chalet_idx   on investors(chalet);

alter table investors enable row level security;

do $$
begin
  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where p.proname = 'current_owner_id' and n.nspname = 'public'
  ) then
    drop policy if exists investors_tenant_isolation on investors;
    execute $sql$
      create policy investors_tenant_isolation on investors for all
        using (owner_id = current_owner_id() or is_platform_admin())
        with check (owner_id = current_owner_id() or is_platform_admin())
    $sql$;
  else
    drop policy if exists investors_authenticated on investors;
    create policy investors_authenticated on investors for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;
end $$;
