-- إدارة المستثمرين: لكل شاليه أعضاء مختلفين ونسب أرباح مختلفة.
create table if not exists investors (
  id         bigint generated by default as identity primary key,
  chalet     text not null,
  name       text not null,
  phone      text,
  percentage numeric not null default 0 check (percentage >= 0 and percentage <= 100),
  note       text,
  owner_id   uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists investors_owner_id_idx on investors(owner_id);
create index if not exists investors_chalet_idx   on investors(chalet);

alter table investors enable row level security;

do $$
begin
  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where p.proname = 'current_owner_id' and n.nspname = 'public'
  ) then
    drop policy if exists investors_tenant_isolation on investors;
    execute $sql$
      create policy investors_tenant_isolation on investors for all
        using (owner_id = current_owner_id() or is_platform_admin())
        with check (owner_id = current_owner_id() or is_platform_admin())
    $sql$;
  else
    drop policy if exists investors_authenticated on investors;
    create policy investors_authenticated on investors for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;
end $$;
